apiVersion: app/v1
kind: Deployment
metadata:
  name: apache-deploy
  labels:
    name: apache-deploy
    app: own-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apache-pod
      app: own-app
  templates:
    metadata:
      name: apache-pod
      labels:
        name: apache-pod
        app: own-app
    spec: 
      containers:
        - name: apache-pod
          image: vpwnd669/own-apache
---

apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: own-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: own-app
  templates:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: own-app
    spec: 
      containers:
        - name: mysql-pod
          image: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
